version: "3.7"

services:
  web:
    container_name: web
    image: dict-web
    ports:
      - 5000:5000
  api:
    container_name: api
    image: dict-api
    ports:
      - 8080:8080
  ng:
    container_name: ng
    image: nginx
    ports:
      - 80:88
    depends_on:
      - web
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/data:/data
        #  - ./access.log:/var/log/nginx/access.log

